In [7]:
import pandas as pd

path = "../data/raw/dfp_cia_aberta_BPA_con_2025.csv"
df = pd.read_csv(path, sep=';', encoding='latin-1')
df.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,02.635.522/0001-95,2025-03-31,1,JALLES MACHADO S.A.,25496,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2024-03-31,1,Ativo Total,6701940.0,S
1,02.635.522/0001-95,2025-03-31,1,JALLES MACHADO S.A.,25496,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1,Ativo Total,7137606.0,S
2,02.635.522/0001-95,2025-03-31,1,JALLES MACHADO S.A.,25496,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2024-03-31,1.01,Ativo Circulante,2120283.0,S
3,02.635.522/0001-95,2025-03-31,1,JALLES MACHADO S.A.,25496,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2025-03-31,1.01,Ativo Circulante,2301201.0,S
4,02.635.522/0001-95,2025-03-31,1,JALLES MACHADO S.A.,25496,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2024-03-31,1.01.01,Caixa e Equivalentes de Caixa,1049863.0,S

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CNPJ_CIA       1240 non-null   object
 1   DT_REFER       1240 non-null   object
 2   VERSAO         1240 non-null   int64
 3   DENOM_CIA      1240 non-null   object
 4   CD_CVM         1240 non-null   int64
 5   GRUPO_DFP      1240 non-null   object
 6   MOEDA          1240 non-null   object
 7   ESCALA_MOEDA   1240 non-null   object
 8   ORDEM_EXERC    1240 non-null   object
 9   DT_FIM_EXERC   1240 non-null   object
 10  CD_CONTA       1240 non-null   object
 11  DS_CONTA       1240 non-null   object
 12  VL_CONTA       1240 non-null   float64
 13  ST_CONTA_FIXA  1240 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 135.8+ KB

In [9]:
df.describe()

       VERSAO        CD_CVM      VL_CONTA
count  1240.0   1240.000000  1.240000e+03
mean      1.0  22332.895161  7.505711e+06
std       0.0   4836.523076  5.448989e+07
min       1.0   9539.000000  0.000000e+00
25%       1.0  20516.000000  0.000000e+00
50%       1.0  23981.000000  7.768500e+03
75%       1.0  25496.000000  5.204848e+05
max       1.0  26522.000000  1.024919e+09

In [10]:
df['CNPJ_CIA'].nunique()

9

In [12]:
df['DS_CONTA'].value_counts().head(10)

DS_CONTA
Aplicações Financeiras Avaliadas a Valor Justo através do Resultado                        36
Títulos Designados a Valor Justo                                                           36
Estoques                                                                                   36
Clientes                                                                                   36
Contas a Receber                                                                           36
Aplicações Financeiras Avaliadas ao Custo Amortizado                                       36
Aplicações Financeiras Avaliadas a Valor Justo através de Outros Resultados Abrangentes    36
Outras Contas a Receber                                                                    36
Ativos Não-Correntes a Venda                                                               36
Despesas Antecipadas                                                                       36
Name: count, dtype: int64